#!/usr/bin/env python3
"""Generate the shared browser/Node 09k converter and firmware include.

The readable algorithm lives in ``web/bwry09k_core.template.js``.  This script
adds the one expensive-but-static asset:

* the exact 64x64 void-and-cluster mask used by the Python 09k recipe.

The measured gamut candidates are generated directly by JavaScript from the
four ink vertices. This keeps browser conversion algorithmic rather than LUT
approximated while still sharing the exact same source with the firmware page.
"""

from __future__ import annotations

import argparse
import base64
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
BW_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(BW_ROOT))

from bwry.bluenoise import void_and_cluster  # noqa: E402

TEMPLATE = BW_ROOT / "web" / "bwry09k_core.template.js"
WEB_CORE = ROOT / "docs" / "bwry09k_core.js"
FIRMWARE_INC = (
    ROOT / "firmware" / "main" / "ui" / "renderers" / "rawdraw" / "bwry09k_web.inc"
)


def _b64_le_u16(values: np.ndarray) -> str:
    return base64.b64encode(np.asarray(values, dtype="<u2").tobytes()).decode("ascii")


def build_mask() -> str:
    mask = void_and_cluster(64, 1.9)
    ranks = np.rint(mask * mask.size - 0.5).astype(np.uint16)
    return _b64_le_u16(ranks)


def render_core() -> str:
    template = TEMPLATE.read_text()
    mask_b64 = build_mask()
    replacements = {
        "__BLUE_NOISE_RANKS_BASE64__": mask_b64,
    }
    for old, new in replacements.items():
        if old not in template:
            raise RuntimeError(f"template placeholder missing: {old}")
        template = template.replace(old, new)
    return template


def firmware_literal(core: str) -> str:
    if ")BWRY09K\"" in core:
        raise RuntimeError("generated JavaScript collides with C++ raw string delimiter")
    return (
        "// Generated by tools/bwry/generate_web_converter.py; do not edit.\n"
        'R"BWRY09K(\n' + core.rstrip() + '\n)BWRY09K"\n'
    )


def update(path: Path, content: str, check: bool) -> bool:
    current = path.read_text() if path.exists() else None
    if current == content:
        print(f"ok {path.relative_to(ROOT)}")
        return True
    if check:
        print(f"stale {path.relative_to(ROOT)}")
        return False
    path.write_text(content)
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files differ")
    args = parser.parse_args()

    core = render_core()
    ok = update(WEB_CORE, core, args.check)
    ok = update(FIRMWARE_INC, firmware_literal(core), args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
